### ISSUE TITLE
疑惑？？

### ISSUE THREAD

**Issue by hackerxiaobai** [weizhepei/CasRel#1]
#### 作者你好，你这个论文和苏建林的这篇博客有什么区别 [博客](https://kexue.fm/archives/6671)

**Comment by weizhepei** [comment]
Yes, the tagging scheme has been introduced in the author's blog before our paper gets published. In this paper, we start with a principled formulation of relational triple extraction and propose a general algorithmic framework that is free from the overlapping triple problem by modeling relations as functions that map subjects to objects. Extensive experiments show that our framework substantially outperforms existing methods by a large margin in various scenarios. We are excited to share this work with researchers and practitioners. Feel free to reopen this issue whenever you have any new questions.

**Comment by verylittlewhite** [comment]
@hackerxiaobai 苏剑林也是这篇论文的作者……
