### ISSUE TITLE
与HBT相比，CasRel模型是在哪里有改动，导致f1又有提升的呢？

### ISSUE THREAD

**Issue by jxyxiangyu** [weizhepei/CasRel#10]
与HBT相比，CasRel模型是在哪里有改动，导致f1又有提升的呢？

**Comment by weizhepei** [comment]
Actually, it's the same model. We only change the name from "HBT" to "CasRel" according to the recommendation of the reviewers. The performance fluctuation is trivial, it might come from different training time, different batch size, or the randomness of DNN itself, etc. As for the final edition, please refer to the released code and the published paper in ACL anthology or the latest preprint on Arxiv.
