### ISSUE TITLE
数据解析的问题

### ISSUE THREAD

**Issue by zjuqiushi** [weizhepei/CasRel#11]
你好，这一行的i和外层循环的i冲突了吧？直接运行程序会报list out of index的错误，请看一下代码
https://github.com/weizhepei/CasRel/blob/e04924c50e9af97d7265c3bfc39455cbe61a5dc2/data/NYT/raw_NYT/generate.py#L53

**Comment by weizhepei** [comment]
Thanks for pointing this out. The generate.py works fine for me, but it would be better to change the above code to something like:
``` tokens = [word_dict[id] for id in sents[i]] ```
