### ISSUE TITLE
HBTokenizer

### ISSUE THREAD

**Issue by transformerzhou** [weizhepei/CasRel#13]
class HBTokenizer(Tokenizer):
    def _tokenize(self, text):
        if not self._cased:
            text = unicodedata.normalize('NFD', text)
            text = ''.join([ch for ch in text if unicodedata.category(ch) != 'Mn'])
            text = text.lower()
        spaced = ''
        for ch in text:
            if ord(ch) == 0 or ord(ch) == 0xfffd or self._is_control(ch):
                continue
            else:
                spaced += ch
        tokens = []
        for word in spaced.strip().split():
            tokens += self._word_piece_tokenize(word)
            tokens.append('[unused1]')
        return tokens

请问为什么要加一个'[unused1]'呢

**Comment by weizhepei** [comment]
This is an interesting attempt. Since we utilize WordPiece for tokenization, the intuitive idea is to model the boundary of subwords. We compare the performance between w/ and w/o the special token '[unused1]', and find the former one is quite close (sometimes slightly better) to the latter one.
