### ISSUE TITLE
表2的结果？

### ISSUE THREAD

**Issue by xumeng123** [weizhepei/CasRel#15]
大神你好，请问表2中对于NYT和WebNLG这两个语料都是单个token的subj/obj的结果吗？还是说您在处理的时候只是取了subj/obj的head部分

**Comment by xumeng123** [comment]
因为我看到根据代码处理后的结果都是单个token的subj/obj的三元组

**Comment by xumeng123** [comment]
因为我看到根据预处理代码处理后的数据都是单个token的subj/obj的三元组

**Comment by weizhepei** [comment]
\>> 表2中对于NYT和WebNLG这两个语料都是单个token的subj/obj的结果吗？
Yes, we follow the same setting as previous works for a fair comparison. As for the single-word-entity issue, I hope the discussions in [issue#3](https://github.com/weizhepei/CasRel/issues/3)  and [issue#9](https://github.com/weizhepei/CasRel/issues/9) would be helpful to you.
