### ISSUE TITLE
Keras tensorflow version issue:

### ISSUE THREAD

**Issue by prasad4fun** [weizhepei/CasRel#21]
Hi,

While trying to set up, facing the below issue just before, ! python run.py ---train=True --dataset=NYT
Looks like versioning issues, could you please share requirements.txt or used packages along with the specific versions.

raceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from model import E2EModel, Evaluate
  File "/content/CasRel/model.py", line 2, in <module>
    from keras.layers import *
  File "/usr/local/lib/python3.6/dist-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by sidney1994** [comment]
same issue

**Comment by sidney1994** [comment]
@prasad4fun This problem can be solved by `pip install keras-bert==0.78.0`

**Comment by hdang20** [comment]
@sidney1994 Hi, are you able to finish training the model?

**Comment by sidney1994** [comment]
yes, I can

**Comment by Spico197** [comment]
I've solved the version issue with the settings below:
- tensorflow-gpu==1.13.1
- keras-bert==0.78.0
- keras==2.2.5
- CUDA 10.0 (or install cudatoolkit=10.0 with `conda` command)
- Python 3.6.10

**Comment by Hao-Kailong** [comment]
I've tried many times and finally this setting works with **NO BUG**:

- keras==2.2.0
- tensorflow-gpu==1.13.1
- keras-bert==0.78.0
- keras-transformer==0.33.0
- python==3.7.7

**Comment by zhenpingli** [comment]
> * keras==2.2.0
> * tensorflow-gpu==1.13.1
> * keras-bert==0.78.0
> * keras-transformer==0.33.0
> * python==3.7.7

thank you very much get the right answer.

**Comment by weizhepei** [comment]
I've updated the [requirements](https://github.com/weizhepei/CasRel#requirements). Thank you all for the effort in clarifying the environmental settings!

**Comment by AnwarsaeedDMU** [comment]
> yes, I can

can you help me with #73 and #74
