### ISSUE TITLE
is there a bug in build_data.py, line18? or did i do sth wrong? 

### ISSUE THREAD

**Issue by yulightnight** [weizhepei/CasRel#25]
it says "list indices must be integers or slices, not str"
the sentence is :
    if not a['relationMentions']
and i didn't see relationMentions as a int varible

i look forward to your reply

**Comment by yulightnight** [comment]
> > it says "list indices must be integers or slices, not str"
> > the sentence is :
> > if not a['relationMentions']
> > and i didn't see relationMentions as a int varible
> > i look forward to your reply
> 
> Did you solve this problem？I also encountered the same problem

Nope.

**Comment by zhenpingli** [comment]
same to ,i read the code find . the tutorial is not really map the code to the tutorial

**Comment by zhenpingli** [comment]
> it says "list indices must be integers or slices, not str"
> the sentence is :
> if not a['relationMentions']
> and i didn't see relationMentions as a int varible
> 
> i look forward to your reply

I have read the source code ,and process the code later ,you need to re code the input fill：
    file_name = 'valid.json'
    output = 'new_valid.json'
    output_normal = 'new_valid_normal.json'
    output_epo = 'new_valid_epo.json'
    output_seo = 'new_valid_seo.json'
    with open('relations2id.json', 'r') as f1, open('words2id.json', 'r') as f2:
        rel2id = json.load(f1)
        words2id = json.load(f2)
    rel_dict = {j:i for i,j in rel2id.items()}
    word_dict = {j:i for i,j in words2id.items()}
    load_data(file_name, word_dict, rel_dict, output, output_normal, output_epo, output_seo)
chage it to the form for the train,json test,json. there miss something in the tutorial. i will rewrite it today ,and  try to upload it tomorrow

**Comment by zhenpingli** [comment]
> it says "list indices must be integers or slices, not str"
> the sentence is :
> if not a['relationMentions']
> and i didn't see relationMentions as a int varible
> 
> i look forward to your reply
just change the name in the code line 75-87,change the valid name to test ,or train.then move the json been built to nyt
   ''' b
    file_name = 'valid.json'
    output = 'new_valid.json'
    output_normal = 'new_valid_normal.json'
    output_epo = 'new_valid_epo.json'
    output_seo = 'new_valid_seo.json'
    '''
    '''
    file_name = 'test.json'
    output = 'new_test.json'
    output_normal = 'new_test_normal.json'
    output_epo = 'new_test_epo.json'
    output_seo = 'new_test_seo.json'
    '''
    file_name = 'test.json'
    output = 'new_test.json'
    output_normal = 'new_test_normal.json'
    output_epo = 'new_test_epo.json'
    output_seo = 'new_test_seo.json'

**Comment by zhenpingli** [comment]
> it says "list indices must be integers or slices, not str"
> the sentence is :
> if not a['relationMentions']
> and i didn't see relationMentions as a int varible
> 
> i look forward to your reply

   '''
    file_name = 'valid.json'
    output = 'new_valid.json'
    output_normal = 'new_valid_normal.json'
    output_epo = 'new_valid_epo.json'
    output_seo = 'new_valid_seo.json'
    '''
    '''
    file_name = 'test.json'
    output = 'new_test.json'
    output_normal = 'new_test_normal.json'
    output_epo = 'new_test_epo.json'
    output_seo = 'new_test_seo.json'
    '''
    file_name = 'test.json'
    output = 'new_test.json'
    output_normal = 'new_test_normal.json'
    output_epo = 'new_test_epo.json'
    output_seo = 'new_test_seo.json'

just change the name of valid or test from the line 75 .use train test dev instead of the file name to build new_train.josn .and so on. the move it to NYT

**Comment by yulightnight** [comment]
> > it says "list indices must be integers or slices, not str"
> > the sentence is :
> > if not a['relationMentions']
> > and i didn't see relationMentions as a int varible
> > i look forward to your reply
> 
> '''
> file_name = 'valid.json'
> output = 'new_valid.json'
> output_normal = 'new_valid_normal.json'
> output_epo = 'new_valid_epo.json'
> output_seo = 'new_valid_seo.json'
> '''
> '''
> file_name = 'test.json'
> output = 'new_test.json'
> output_normal = 'new_test_normal.json'
> output_epo = 'new_test_epo.json'
> output_seo = 'new_test_seo.json'
> '''
> file_name = 'test.json'
> output = 'new_test.json'
> output_normal = 'new_test_normal.json'
> output_epo = 'new_test_epo.json'
> output_seo = 'new_test_seo.json'
> 
> just change the name of valid or test from the line 75 .use train test dev instead of the file name to build new_train.josn .and so on. the move it to NYT

thank you pal!
it sounds like the data preprocessing job should be done for triple times.

**Comment by weizhepei** [comment]
Hi all, sorry for the inconvenience. It seems like a preprocessing issue, which has been discussed before. Please refer to this [issue#4](https://github.com/weizhepei/CasRel/issues/4).
