### ISSUE TITLE
one problem about test

### ISSUE THREAD

**Issue by nightzero123** [weizhepei/CasRel#26]
since after training,  only hbt model was saved; then when test, how can we load the subject and object model?

**Comment by weizhepei** [comment]
The proposed model is an end-to-end (E2E) model with two modules (namely subject_model and object_model in code).

For training:
Please refer to https://github.com/weizhepei/CasRel/blob/master/run.py#L49 and https://github.com/weizhepei/CasRel/blob/master/model.py#L97 for details on how we train and save the E2E model.

For testing:
Please refer to https://github.com/weizhepei/CasRel/blob/master/run.py#L55 and https://github.com/weizhepei/CasRel/blob/master/utils.py#L94 for details on how we load and test the E2E model.
