### ISSUE TITLE
CopyRL model inplementation

### ISSUE THREAD

**Issue by Hao-Kailong** [weizhepei/CasRel#27]
Hello, @weizhepei , in your paper you mentioned that you have implemented CopyRE(with Reinforcement Learning)? Could you make it public? Thanks a lot.

**Comment by weizhepei** [comment]
Hi, @Hao-Kailong. In fact, CopyR_RL has an official open-sourced code [here](https://github.com/xiangrongzeng/multi_re). I didn't rewrite the CopyR_RL model from scratch but directly use the publicly released code and reproduce the performance. The reason behind this is that they didn't report detailed results on different types of sentences in the [original paper](https://www.aclweb.org/anthology/D19-1035.pdf). For a fair comparison, we use our version (marked with *) to represent the CopyR_RL method in Table 3 and Figure 3. We also list the overall performance of both CopyR_RL and CopyR_RL\* in Table 2, from which we can find the performance fluctuation is trivial. You can rely on the official open-sourced code for further use.
