### ISSUE TITLE
os.environ["CUDA_VISIBLE_DEVICES"] = "1"  kernel version seems to match DSO: 410.129.0

### ISSUE THREAD

**Issue by zhenpingli** [weizhepei/CasRel#28]
os.environ["CUDA_VISIBLE_DEVICES"] = "1" 
this shoud be change to 
###os.environ["CUDA_VISIBLE_DEVICES"] = "1" 
or 
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
when error happen , or you should change it by your own device

**Comment by weizhepei** [comment]
For those who have only one GPU device, this line should be changed to os.environ["CUDA_VISIBLE_DEVICES"] = "0" by default. Thanks for pointing this out : )
