### ISSUE TITLE
i want to konw which keras-bert you used

### ISSUE THREAD

**Issue by zhenpingli** [weizhepei/CasRel#29]

**Comment by zhenpingli** [comment]
Hao-Kailong commented 21 days ago
I've tried many times and finally this setting works with NO BUG:

keras==2.2.0
tensorflow-gpu==1.13.1
keras-bert==0.78.0
keras-transformer==0.33.0
python==3.7.7

Hao-Kailong give the right answer.thank you @Hao-Kailong

**Comment by weizhepei** [comment]
I've updated the requirements, please refer to https://github.com/weizhepei/CasRel#requirements.
