### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Amling2017** [weizhepei/CasRel#4]
Traceback (most recent call last):
  File "build_data.py", line 18, in <module>
    if not a['relationMentions']:
TypeError: list indices must be integers or slices, not str

How to solve this problem?

**Comment by weizhepei** [comment]
Have you processed the numerical data (e.g., valid.json) under raw_NYT/ and move the output files (e.g., new_valid.json) to NYT/ ? Perhaps you need to rename the "new_valid.json" to "valid.json" under NYT/ to be consistent with the hardcoded file name in build_data.py?

**Comment by Amling2017** [comment]
你好！文件格式是这样的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhepei Wei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月17日(星期天) 晚上10:44
收件人:&nbsp;"weizhepei/CasRel"<CasRel@noreply.github.com&gt;;
抄送:&nbsp;"Haley"<1564643312@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [weizhepei/CasRel] TypeError: list indices must be integers or slices, not str (#4)





 
Have you processed the numerical data (e.g., valid.json) under raw_NYT/ and move the output files (e.g., new_valid.json) to NYT/ ? Perhaps you need to rename the "new_valid.json" to "valid.json" under NYT/ to be consistent with the hardcoded file name in build_data.py?

**Comment by weizhepei** [comment]
That's weird. Could you please share your converted files to me (through email/Google Drive/Baidu Netdisk, etc.) so that I can check this out?

**Comment by weizhepei** [comment]
@Amling2017 Thanks for the email, I've checked the files that you sent to me. Below are some suggestions:
1. Change the file_name (which is "valid.json" by default) to "train.json" or "test.json" at Line 74 ~ 78 in generate.py, then run the .py file to get "new_valid.json", "new_train.json" and "new_test.json".
2. Move the output "new_train.json", "new_valid.json" and "new_test.json" to NYT/, then rename the three files as "train.json", "dev.json" and "test.json".
3. Run build_data.py to get "train_triples.json", "dev_triples.json" and "test_triples.json".

**Comment by Amling2017** [comment]
Ok,Thank you!



发自我的iPhone


------------------ Original ------------------
