### ISSUE TITLE
inferece过程的解码是否有问题

### ISSUE THREAD

**Issue by Coder-nlper** [weizhepei/CasRel#5]
hello～
我通读了你的论文和代码。有点想不通的就是inference这块。
subject中，
我看到，np.where(sub_heads_logits[0] > h_bar)[0], np.where(sub_tails_logits[0] > t_bar)[0]
取出来了所有的heads和tails
heads = [0,1]
tails = [4, 5]
最终组合的结果是
[0,4] [0,5], [1,4], [1,5]
**怎么排除错误的subject？**
而且预测object的时候
sub_heads, sub_tails = np.array([sub[1:] for sub in subjects]).T.reshape((2, -1, 1))
送入object_net的是多个头和尾的位置，seq_gather应该会有问题吧。按照你suject的循环，
obj_heads, obj_tails = np.where(obj_heads_logits[i] > h_bar), np.where(obj_tails_logits[i] > t_bar)
**这里是通过i取出当前subject对应head或者tail的结果，但是这个obj_tails_logits貌似没有这一维度啊？**

**Comment by Coder-nlper** [comment]
实体重叠问题也包含了。这个问题目前不在讨论范围内～

**Comment by caoxu915683474** [comment]
你好，我也有这个问题，请问你是怎么考虑的呀，求教！
