### ISSUE TITLE
解码过程有点问题

### ISSUE THREAD

**Issue by xumeng123** [weizhepei/CasRel#6]
请问模型是如何解决的以下问题的呢，真心求解答，在代码里没看出来：
1. 实体的head重叠，比如"北京市政府"与"北京大学"，代码里对每一个subjet/object的head,取的都是最近的tail,因此以上问题是否解决不了？

**Comment by weizhepei** [comment]
Hi, Xu Meng. I don't see how the heads of the two entities overlap in the same sentence. Could you please be more specific by giving a demo sentence, such as "北京市政府xxxx, bla..bla.., 北京大学xxxx.", or something like that. Thank you.

**Comment by 131250208** [comment]
@weizhepei For example, sentences like "北京市政府正式东迁至通州。". There are two triplets: (北京市政府，位于，通州) and （北京市，包含，通州）。If the model misses one of the two nested head entities, it may miss the whole triplet. I think this is what he wants to ask.

**Comment by xumeng123** [comment]
是的，按照作者的解码方式，(北京市政府，位于，通州) and （北京市，包含，通州）这两个三元组只能找到一个，比如当subj的start为“北”的时候，第一个end为“市” or "府"的任何一个时，start都会往后移动。

**Comment by weizhepei** [comment]
Great example! Now I get it. The recognition of nested entities is a challenging task, our current framework can not solve the nested entity problem.

**Comment by 131250208** [comment]
> 是的，按照作者的解码方式，(北京市政府，位于，通州) and （北京市，包含，通州）这两个三元组只能找到一个，比如当subj的start为“北”的时候，第一个end为“市” or "府"的任何一个时，start都会往后移动。

Hi~, our [new model](https://github.com/131250208/TPlinker-joint-extraction) can handle the nested entity problem, you might want to have a try.
